[[pages]]
path = "pages/top_100_books.py"
name = "Top 100 Trending Books"
icon = "ğŸ“š"
url_path = "top_100_treding_books"

[[pages]]
path = "pages/book_reviews.py"
name = "Books Reviews"
icon = "ğŸ“"
url_path = "books_reviews"